namespace apekade.Models.Enums;

public enum Category
{
  ELECTRONICS,
  HOME_APPLIANCES,
  TOYS_AND_GAMES,
  FASHION_AND_APPAREL,
  STATIONERY_AND_OFFICE_SUPPLIES,
  SPORTS_AND_FITNESS,
  BEAUTY_AND_PERSONAL_CARE,
  BOOKS_AND_MEDIA,
  HEALTH_AND_WELLNESS,
  AUTOMOTIVE,
  HOME_AND_FURNITURE
}
