namespace apekade.Models.Enums;

public enum SubCategory
{
  // Electronics
  MOBILE_PHONES,
  LAPTOPS,
  TABLETS,
  SMART_WATCHES,
  TELEVISIONS,
  CAMERAS,

  // Home Appliances
  KITCHEN_APPLIANCES,
  WASHING_MACHINES,
  AIR_CONDITIONERS,
  VACUUM_CLEANERS,

  // Toys and Games
  ACTION_FIGURES,
  EDUCATIONAL_TOYS,
  BOARD_GAMES,
  OUTDOOR_TOYS,

  // Fashion and Apparel
  MENS_CLOTHING,
  WOMENS_CLOTHING,
  FOOTWEAR,
  ACCESSORIES,

  // Stationery and Office Supplies
  WRITING_INSTRUMENTS,
  NOTEBOOKS_AND_PAPER,
  OFFICE_SUPPLIES,

  // Sports and Fitness
  GYM_EQUIPMENT,
  OUTDOOR_SPORTS,
  CYCLING,

  // Beauty and Personal Care
  SKINCARE,
  MAKEUP,
  HAIR_CARE,

  // Books and Media
  FICTION_BOOKS,
  NON_FICTION_BOOKS,
  MUSIC_AND_CDS,
  MOVIES,

  // Health and Wellness
  SUPPLEMENTS,
  FITNESS_TRACKERS,
  PERSONAL_HYGIENE,

  // Automotive
  CAR_ACCESSORIES,
  MOTORCYCLE_ACCESSORIES,
  TOOLS_AND_EQUIPMENT,

  // Home and Furniture
  LIVING_ROOM_FURNITURE,
  BEDROOM_FURNITURE,
  KITCHEN_FURNITURE
}
